version: '2'

services:
  data_mysql:
    image: busybox
    container_name: crmtest_data_mysql
    volumes:
     -  data_mysql:/var/lib/mysql:z

  data_sugarcrm:
    image: busybox
    container_name: crmtest_data_sugarcrm
    volumes:
     - data_sugarcrm:/var/www/html/sugarcrm:z

  sugarweb:
    image: sugarfactory/c7-sugarcrmstack-for-s7.9:v1.0.6-2
    container_name: crmtest_web
    volumes_from:
     - data_sugarcrm
    volumes:
      - web_logs:/var/log:Z
      - web_hiera_data:/etc/puppet/hieradata:Z
      - web_puppet_data:/etc/puppet/manifests:Z
      - web_puppet_sugarcrmstack:/etc/puppet/modules/sugarcrmstack:Z
      - web_apache_ssh:/var/www/.ssh:Z
    links:
     - sugardatabase
     - sugarmemcached
     - sugarelastic
#    environment:
#     - SUGARCRM_DB_PASSWORD=heslo
    ports:
     - "14080:80"
     - "14443:443"
     - "14022:22"

  sugardatabase:
    image: mysql:5.7
    container_name: crmtest_db
    volumes_from:
     - data_mysql
    ports:
     - "14306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=heslo
     - MYSQL_DATABASE=sugarcrm
     - MYSQL_USER=sugarcrm
     - MYSQL_PASSWORD=sugarpass

  sugarmemcached:
    image: memcached:latest
    container_name: crmtest_memcache
    ports:
     - "14211:11211"

  sugarredis:
    restart: always
    image: redis:latest
    container_name: crmtest_redis
    ports:
     - "16379:6379"

  sugarelastic:
    image: elasticsearch:1.7.6
    container_name: crmtest_elastic
    ports:
     - "14920:9200"

volumes:
  data_mysql:
      driver: local
  data_sugarcrm:
      driver: local
  web_logs:
      driver: local
  web_hiera_data:
      driver: local
  web_puppet_data:
      driver: local
  web_apache_ssh:
      driver: local
  web_puppet_sugarcrmstack:
      driver: local
