# docs
#
# https://forge.etsi.org/gitlab/help/ci/yaml/README.md
# https://about.gitlab.com/2017/07/11/dockerizing-review-apps/
# https://gitlab.com/SugarFactory/docker-c7-sugarcrmstack-for-s7.9
#
stages:
  - build
#
build:
  stage: build
  script:
    - echo "Building the image"
    - docker build -t sugarfactory/c7-sugarcrmstack-for-s7.9 .
    - docker tag sugarfactory/c7-sugarcrmstack-for-s7.9:latest \
      hub.docker.com/sugarfactory/c7-sugarcrmstack-for-s7.9:$CI_COMMIT_REF_NAME
    - docker push hub.docker.com/sugarfactory/c7-sugarcrmstack-for-s7.9:$CI_COMMIT_REF_NAME
  only:
  - master
