apiVersion: v1
kind: Service
metadata:
  name: sugarcrmstack79-mysql
  labels:
    app: sugarcrmstack79
    tier: backend
spec:
  ports:
  - port: 13306
    targetPort: 3306
  selector:
    app: sugarcrmstack79-mysql
    tier: backend

